services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--log.level=DEBUG"  # Add debug logging
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=admin@devbppk.my.id"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    restart: always

  django:
    build:
      context: ./src
    volumes:
      - ./src:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    expose:
      - 8000
    restart: always
    labels:
      # Remove redirect temporarily
      - "traefik.http.routers.django-http.middlewares=noop@internal"
      - "traefik.enable=true"
      # Router for HTTPS
      - "traefik.http.routers.django.rule=Host(`www.stage.devbppk.my.id`) || Host(`stage.devbppk.my.id`)"
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.tls=true"
      - "traefik.http.routers.django.tls.certresolver=myresolver"
      - "traefik.http.services.django.loadbalancer.server.port=8000"

      # HTTP to HTTPS Redirect
      - "traefik.http.routers.django-http.rule=Host(`www.stage.devbppk.my.id`) || Host(`stage.devbppk.my.id`)"
      - "traefik.http.routers.django-http.entrypoints=web"
      - "traefik.http.routers.django-http.middlewares=django-https-redirect"
      - "traefik.http.middlewares.django-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.django-https-redirect.redirectscheme.permanent=true"
  traefik-dashboard:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.stage.devbppk.my.id`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      # Generate htpasswd: `htpasswd -nb admin password`
      - "traefik.http.middlewares.auth.basicauth.users=admin:$apr1$BdmnTc8T$.ItXwT3P9hQrHspZhsD.S/"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always

volumes:
  static_volume:
  media_volume:
