# Generated by Django 5.1.2 on 2024-10-20 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_usercourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'ordering': ['joined_at'], 'verbose_name_plural': 'Courses Students'},
        ),
        migrations.AlterModelTable(
            name='usercourse',
            table='course_users',
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.lesson')),
                ('user_course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.usercourse')),
            ],
            options={
                'verbose_name_plural': 'Courses Progress',
                'db_table': 'course_user_progress',
                'ordering': ['completed_at'],
            },
        ),
    ]
