# Generated by Django 5.1.2 on 2024-10-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_usercourse_options_alter_usercourse_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseprogress',
            name='completed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
