# Generated by Django 5.1.2 on 2024-11-18 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_usercourseprogress_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['title'], 'verbose_name': 'Classrooms', 'verbose_name_plural': 'Classrooms'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['course', 'order'], 'verbose_name_plural': 'Courses Modules'},
        ),
        migrations.AlterModelOptions(
            name='userclassroom',
            options={'ordering': ['joined_at'], 'verbose_name': 'Classrooms User', 'verbose_name_plural': 'Classrooms Users'},
        ),
        migrations.CreateModel(
            name='ClassroomTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.classroom')),
            ],
            options={
                'verbose_name': 'Classrooms Task',
                'verbose_name_plural': 'Classrooms Tasks',
                'db_table': 'classroom_task',
                'ordering': ['completed', '-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserClassroomTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, default=0, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_classroom', to='learning.classroomtask')),
                ('user_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.userclassroom')),
            ],
            options={
                'verbose_name': 'Classrooms User Task',
                'verbose_name_plural': 'Classrooms Users Tasks',
                'db_table': 'classroom_user_task',
                'ordering': ['user_classroom', 'task'],
            },
        ),
    ]
